import { useEffect, useState } from "react";

const API_URL = import.meta.env.VITE_API_URL || "http://localhost:8787";
async function request(path, options = {}, token) {
  const response = await fetch(`${API_URL}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } });
  const body = await response.json();
  if (!response.ok) throw new Error(body.error || "Request failed.");
  return body;
}

export default function ShoppingCopilot() {
  const [session, setSession] = useState(() => JSON.parse(localStorage.getItem("affili-session") || "null"));
  const [mode, setMode] = useState("login"), [email, setEmail] = useState(""), [password, setPassword] = useState("");
  const [conversations, setConversations] = useState([]), [conversationId, setConversationId] = useState(null), [messages, setMessages] = useState([]);
  const [draft, setDraft] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const loadConversations = async () => setConversations((await request("/api/conversations", {}, session.token)).conversations);
  useEffect(() => { if (session) loadConversations().catch((cause) => setError(cause.message)); }, [session]);
  const authenticate = async (event) => { event.preventDefault(); setError(""); setBusy(true); try { const data = await request(`/api/auth/${mode}`, { method: "POST", body: JSON.stringify({ email, password }) }); const next = { token: data.token, user: data.user }; localStorage.setItem("affili-session", JSON.stringify(next)); setSession(next); setPassword(""); } catch (cause) { setError(cause.message); } finally { setBusy(false); } };
  const openConversation = async (id) => { setError(""); setBusy(true); try { const data = await request(`/api/conversations/${id}/messages`, {}, session.token); setConversationId(id); setMessages(data.messages); } catch (cause) { setError(cause.message); } finally { setBusy(false); } };
  const send = async (event) => { event.preventDefault(); const text = draft.trim(); if (!text || busy) return; setDraft(""); setError(""); setBusy(true); const temporary = { id: "pending", role: "user", content: text, sources: [] }; setMessages((current) => [...current, temporary]); try { const data = await request("/api/chat", { method: "POST", body: JSON.stringify({ message: text, conversationId }) }, session.token); setConversationId(data.conversationId); setMessages((current) => [...current.filter((message) => message.id !== "pending"), data.message]); loadConversations(); } catch (cause) { setMessages((current) => current.filter((message) => message.id !== "pending")); setDraft(text); setError(cause.message); } finally { setBusy(false); } };

  if (!session) return <section className="copilot-shell card"><div className="copilot-intro"><p className="section-label">AI SHOPPING COPILOT</p><h2>Find the right product, with evidence</h2><p>Sign in to save your conversations and ask questions against the curated affiliate catalog.</p></div><form className="auth-form" onSubmit={authenticate}><div className="auth-switch"><button type="button" className={mode === "login" ? "active" : ""} onClick={() => setMode("login")}>Sign in</button><button type="button" className={mode === "register" ? "active" : ""} onClick={() => setMode("register")}>Create account</button></div><input type="email" placeholder="Email address" value={email} onChange={(event) => setEmail(event.target.value)} required /><input type="password" placeholder="Password (8+ characters)" value={password} onChange={(event) => setPassword(event.target.value)} minLength="8" required /><button className="btn btn-primary" disabled={busy}>{busy ? "Please wait…" : mode === "login" ? "Sign in" : "Create account"}</button>{error && <p className="form-error">{error}</p>}</form></section>;
  return <section className="copilot-shell card"><aside className="chat-sidebar"><div><p className="section-label">AI SHOPPING COPILOT</p><button className="new-chat" onClick={() => { setConversationId(null); setMessages([]); }}>+ New chat</button></div><div className="conversation-list">{conversations.map((conversation) => <button key={conversation.id} className={conversation.id === conversationId ? "conversation active" : "conversation"} onClick={() => openConversation(conversation.id)}>{conversation.title}</button>)}</div><button className="sign-out" onClick={() => { localStorage.removeItem("affili-session"); setSession(null); }}>Sign out · {session.user.email}</button></aside><div className="chat-panel"><div className="chat-heading"><div><h2>Shopping Copilot</h2><p>RAG-grounded answers from your product catalog.</p></div><span className="live-pulse-badge">PRIVATE HISTORY</span></div><div className="chat-thread">{messages.length === 0 && <div className="chat-empty"><strong>What are you shopping for?</strong><span>Try: “Which laptop accessory is best for an external display?”</span></div>}{messages.map((message) => <article className={`chat-message ${message.role}`} key={message.id}><div>{message.content}</div>{message.sources?.length > 0 && <div className="source-list">Sources: {message.sources.map((source) => <span key={source.id}>{source.title}</span>)}</div>}</article>)}{busy && <div className="chat-message assistant">Thinking with the product catalog…</div>}</div><form className="chat-composer" onSubmit={send}><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Ask about products, compatibility, or affiliate disclosure…" maxLength="2000" /><button className="btn btn-primary" disabled={busy || !draft.trim()}>Send</button></form>{error && <p className="form-error">{error}</p>}</div></section>;
}
